if(DEFINED CPP_LKM_KERNEL_BUILD_DIR AND NOT "${CPP_LKM_KERNEL_BUILD_DIR}" STREQUAL "")
    return()
endif()

if(DEFINED KBUILD_DIR AND NOT "${KBUILD_DIR}" STREQUAL "")
    set(CPP_LKM_KERNEL_BUILD_DIR "${KBUILD_DIR}")
    if(CMAKE_CURRENT_FUNCTION)
        set(CPP_LKM_KERNEL_BUILD_DIR "${KBUILD_DIR}" PARENT_SCOPE)
    endif()
    return()
endif()

execute_process(
    COMMAND uname -r
    OUTPUT_VARIABLE CPP_LKM_KERNEL_RELEASE
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(CPP_LKM_KERNEL_BUILD_DIR "/lib/modules/${CPP_LKM_KERNEL_RELEASE}/build")
if(CMAKE_CURRENT_FUNCTION)
    set(CPP_LKM_KERNEL_BUILD_DIR "/lib/modules/${CPP_LKM_KERNEL_RELEASE}/build" PARENT_SCOPE)
endif()
