if(BUILD_MODE STREQUAL "host")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "16.0")
        message(FATAL_ERROR "Host Clang must be 16+")
    endif()
    if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS "13.0")
        message(FATAL_ERROR "Host GCC must be 13+")
    endif()
elseif(BUILD_MODE STREQUAL "platform" OR BUILD_MODE STREQUAL "ci")
    if(NOT CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        message(FATAL_ERROR "Platform mode requires GCC")
    endif()
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "12.0" OR CMAKE_CXX_COMPILER_VERSION
                                                         VERSION_GREATER_EQUAL "13.0"
    )
        message(FATAL_ERROR "Platform mode requires GCC 12.x")
    endif()
endif()
