name: ci

on:
  push:
  pull_request:

jobs:
  host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-format g++

      - name: Configure (host)
        run: cmake -B build -DBUILD_MODE=host -DBUILD_KO=OFF

      - name: Build
        run: cmake --build build -j

      - name: Test
        run: ctest --test-dir build -V

      - name: Format check
        run: cmake --build build --target format-check
